---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        image: 992382639259.dkr.ecr.eu-north-1.amazonaws.com/kaam25:96366634754672d8708e81d2a09ec1f58d8d8705
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myntra-service
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
